"""Report rendering — HTML template and PDF generation from case snapshots."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any, Dict

import markdown as md_lib


# ---------------------------------------------------------------------------
# HTML template (inline CSS — self-contained for download and xhtml2pdf)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title}</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 13px;
    line-height: 1.6;
    color: #1e293b;
    background: #ffffff;
    margin: 0;
    padding: 32px 48px;
  }}
  h1 {{ font-size: 22px; color: #0f172a; margin: 0 0 4px; }}
  h2 {{ font-size: 15px; color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin: 28px 0 10px; }}
  h3 {{ font-size: 13px; color: #334155; margin: 16px 0 6px; }}
  .meta {{ color: #64748b; font-size: 12px; margin-bottom: 24px; }}
  .badge {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 99px;
    font-size: 11px;
    font-weight: 600;
    margin-right: 4px;
  }}
  .badge-blue   {{ background: #dbeafe; color: #1d4ed8; }}
  .badge-green  {{ background: #dcfce7; color: #15803d; }}
  .badge-red    {{ background: #fee2e2; color: #b91c1c; }}
  .badge-amber  {{ background: #fef3c7; color: #b45309; }}
  .badge-slate  {{ background: #f1f5f9; color: #475569; }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 8px 0 16px;
    font-size: 12px;
  }}
  th {{
    background: #f8fafc;
    text-align: left;
    padding: 6px 10px;
    color: #475569;
    font-weight: 600;
    border-bottom: 2px solid #e2e8f0;
  }}
  td {{
    padding: 6px 10px;
    border-bottom: 1px solid #f1f5f9;
    vertical-align: top;
  }}
  tr:last-child td {{ border-bottom: none; }}
  .timeline-item {{ display: flex; gap: 12px; margin-bottom: 12px; }}
  .timeline-dot {{
    width: 8px; height: 8px;
    border-radius: 50%;
    background: #3b82f6;
    margin-top: 5px;
    flex-shrink: 0;
  }}
  .note-block {{
    background: #f8fafc;
    border-left: 3px solid #3b82f6;
    padding: 8px 12px;
    margin-bottom: 8px;
    border-radius: 0 4px 4px 0;
    font-size: 12px;
  }}
  .note-meta {{ color: #94a3b8; font-size: 11px; margin-bottom: 2px; }}
  .footer {{
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    color: #94a3b8;
    font-size: 11px;
  }}
  .confidence-bar-bg {{
    background: #e2e8f0;
    border-radius: 4px;
    height: 6px;
    width: 80px;
    display: inline-block;
    vertical-align: middle;
  }}
  .confidence-bar-fill {{
    background: #3b82f6;
    border-radius: 4px;
    height: 6px;
  }}
</style>
</head>
<body>

<h1>{title}</h1>
<div class="meta">
  <span class="badge badge-{status_cls}">{status}</span>
  <span class="badge badge-{priority_cls}">{priority}</span>
  &nbsp;·&nbsp; {case_number} &nbsp;·&nbsp; Generated {generated_at}
</div>

{description_block}

<h2>Scan Summary</h2>
{scans_block}

{indicators_block}

{relationships_block}

{timeline_block}

{notes_block}

{followup_block}

<div class="footer">
  Generated by OSIF v2 &nbsp;·&nbsp; {generated_at} &nbsp;·&nbsp; {title}
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_STATUS_CLS = {"open": "blue", "active": "green", "closed": "slate", "archived": "slate"}
_PRIORITY_CLS = {"critical": "red", "high": "amber", "medium": "blue", "low": "slate"}


def _fmt_dt(value) -> str:
    if not value:
        return "n/a"
    if isinstance(value, str):
        return value[:19].replace("T", " ")
    return value.strftime("%Y-%m-%d %H:%M")


def _conf_bar(confidence) -> str:
    try:
        pct = int(float(confidence) * 100)
    except (TypeError, ValueError):
        pct = 0
    fill = max(0, min(100, pct))
    return (
        f'<span class="confidence-bar-bg">'
        f'<span class="confidence-bar-fill" style="width:{fill}%"></span>'
        f'</span> <span style="font-size:11px;color:#64748b">{pct}%</span>'
    )


def _scans_table(scans: list) -> str:
    if not scans:
        return "<p style='color:#94a3b8'>No scans have been run for this case.</p>"
    rows = ""
    for s in scans:
        status_cls = {"completed": "green", "partial": "amber", "failed": "red"}.get(s.get("status", ""), "slate")
        rows += (
            f"<tr>"
            f"<td>{s.get('seed_value','')}</td>"
            f"<td><span class='badge badge-blue'>{s.get('seed_kind','')}</span></td>"
            f"<td><span class='badge badge-{status_cls}'>{s.get('status','')}</span></td>"
            f"<td>{s.get('progress',0)}/{s.get('total_modules',0)}</td>"
            f"<td style='color:#94a3b8;font-size:11px'>{_fmt_dt(s.get('created_at'))}</td>"
            f"</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Target</th><th>Kind</th><th>Status</th><th>Modules</th><th>Started</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table>"
    )


def _indicators_table(indicators: list, report_type: str) -> str:
    if report_type not in {"technical", "full", "summary"}:
        return ""
    if not indicators:
        return "<h2>Indicators</h2><p style='color:#94a3b8'>No indicators found.</p>"
    rows = ""
    for ind in indicators[:50]:
        kind_cls = {
            "domain": "blue", "ip": "green", "email": "amber",
            "hostname": "slate", "url": "slate",
        }.get(ind.get("kind", ""), "slate")
        rows += (
            f"<tr>"
            f"<td><span class='badge badge-{kind_cls}'>{ind.get('kind','')}</span></td>"
            f"<td style='font-family:monospace'>{ind.get('value','')}</td>"
            f"<td>{_conf_bar(ind.get('confidence', 0))}</td>"
            f"<td style='color:#94a3b8;font-size:11px'>{ind.get('source_module','')}</td>"
            f"</tr>"
        )
    return (
        "<h2>Indicators</h2>"
        "<table><thead><tr>"
        "<th>Kind</th><th>Value</th><th>Confidence</th><th>Source</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table>"
    )


def _relationships_table(edges: list, indicator_map: dict, report_type: str) -> str:
    if report_type not in {"technical", "full"}:
        return ""
    if not edges:
        return "<h2>Relationships</h2><p style='color:#94a3b8'>No relationships found.</p>"
    rows = ""
    for e in edges[:50]:
        src = indicator_map.get(str(e.get("src_id", "")), {})
        dst = indicator_map.get(str(e.get("dst_id", "")), {})
        rows += (
            f"<tr>"
            f"<td style='font-family:monospace'>{src.get('value', str(e.get('src_id','')))}</td>"
            f"<td style='color:#3b82f6;font-weight:600'>{e.get('relationship_type','')}</td>"
            f"<td style='font-family:monospace'>{dst.get('value', str(e.get('dst_id','')))}</td>"
            f"<td style='color:#94a3b8;font-size:11px'>{e.get('source_module','')}</td>"
            f"<td>{_conf_bar(e.get('confidence', 0))}</td>"
            f"</tr>"
        )
    return (
        "<h2>Relationships</h2>"
        "<table><thead><tr>"
        "<th>Source</th><th>Relationship</th><th>Target</th><th>Module</th><th>Confidence</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table>"
    )


def _timeline_block(case_data: dict, scans: list, report_type: str) -> str:
    if report_type not in {"timeline", "full"}:
        return ""
    events = [{"time": case_data.get("created_at", ""), "label": "Case created", "detail": case_data.get("title", "")}]
    for s in scans:
        events.append({"time": s.get("created_at", ""), "label": f"Scan started: {s.get('seed_value','')}", "detail": s.get("seed_kind", "")})
        if s.get("finished_at"):
            events.append({"time": s.get("finished_at", ""), "label": f"Scan {s.get('status','done')}: {s.get('seed_value','')}", "detail": ""})
    events.sort(key=lambda e: e.get("time") or "")
    items = "".join(
        f"<div class='timeline-item'><div class='timeline-dot'></div><div>"
        f"<div style='font-weight:600'>{ev['label']}</div>"
        f"<div style='color:#64748b;font-size:12px'>{ev.get('detail','')} &nbsp;·&nbsp; {_fmt_dt(ev['time'])}</div>"
        f"</div></div>"
        for ev in events
    )
    return f"<h2>Timeline</h2>{items}"


def _notes_block(notes: list) -> str:
    if not notes:
        return "<h2>Notes</h2><p style='color:#94a3b8'>No case notes recorded.</p>"
    blocks = "".join(
        f"<div class='note-block'>"
        f"<div class='note-meta'>{_fmt_dt(n.get('created_at'))} · {n.get('author') or 'Analyst'}</div>"
        f"{n.get('content','')}"
        f"</div>"
        for n in notes
    )
    return f"<h2>Notes</h2>{blocks}"


def _followup_block(edges: list, scans: list, report_type: str) -> str:
    if report_type not in {"summary", "full"}:
        return ""
    items = []
    high_signal = [e for e in edges if e.get("relationship_type", "").upper() in
                   {"FOUND_IN_BREACH", "HAS_VULNERABILITY", "FLAGGED_AS", "HAS_REPUTATION"}]
    if high_signal:
        items.append(f"Review {len(high_signal)} high-signal relationship(s) for validation.")
    if any(s.get("status") in {"partial", "failed", "error"} for s in scans):
        items.append("Review failed or partial scans and rerun missing modules where appropriate.")
    items.append("Validate all findings against source evidence before external distribution.")
    rows = "".join(f"<li>{i}</li>" for i in items)
    return f"<h2>Analyst Follow-Up</h2><ul>{rows}</ul>"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_snapshot(case, scans: list, indicators: list, edges: list, notes: list) -> Dict[str, Any]:
    """Build a point-in-time JSON snapshot of the case data."""
    def _ind(i):
        return {
            "id": str(i.id), "kind": i.kind, "value": i.value,
            "confidence": float(i.confidence) if i.confidence is not None else None,
            "source_module": i.source_module,
        }

    def _edge(e):
        return {
            "src_id": str(e.src_id), "dst_id": str(e.dst_id),
            "relationship_type": e.relationship_type,
            "source_module": e.source_module,
            "confidence": float(e.confidence) if e.confidence is not None else None,
        }

    def _scan(s):
        return {
            "id": str(s.id), "seed_value": s.seed_value, "seed_kind": s.seed_kind,
            "status": s.status, "progress": s.progress, "total_modules": s.total_modules,
            "created_at": s.created_at.isoformat() if s.created_at else None,
            "finished_at": s.finished_at.isoformat() if s.finished_at else None,
        }

    def _note(n):
        return {
            "id": str(n.id), "content": n.content,
            "author": getattr(n, "author", None),
            "created_at": n.created_at.isoformat() if n.created_at else None,
        }

    return {
        "case": {
            "id": str(case.id), "case_number": case.case_number, "title": case.title,
            "description": case.description, "status": case.status, "priority": case.priority,
            "assigned_to": case.assigned_to, "client": case.client,
            "closed_reason": getattr(case, "closed_reason", None),
            "created_at": case.created_at.isoformat() if case.created_at else None,
        },
        "scans": [_scan(s) for s in scans],
        "indicators": [_ind(i) for i in indicators],
        "edges": [_edge(e) for e in edges],
        "notes": [_note(n) for n in notes],
        "generated_at": datetime.utcnow().isoformat(),
    }


def render_html(snapshot: Dict[str, Any], title: str, report_type: str) -> str:
    """Render a self-contained HTML report from a snapshot."""
    case     = snapshot.get("case", {})
    scans    = snapshot.get("scans", [])
    inds     = snapshot.get("indicators", [])
    edges    = snapshot.get("edges", [])
    notes    = snapshot.get("notes", [])
    gen_at   = snapshot.get("generated_at", datetime.utcnow().isoformat())

    ind_map = {i["id"]: i for i in inds}

    desc_block = (
        f"<h2>Case Description</h2><p>{case.get('description','')}</p>"
        if case.get("description") else ""
    )

    html = _HTML_TEMPLATE.format(
        title=title,
        case_number=case.get("case_number", ""),
        status=case.get("status", ""),
        status_cls=_STATUS_CLS.get(case.get("status", ""), "slate"),
        priority=case.get("priority", ""),
        priority_cls=_PRIORITY_CLS.get(case.get("priority", ""), "slate"),
        generated_at=_fmt_dt(gen_at),
        description_block=desc_block,
        scans_block=_scans_table(scans),
        indicators_block=_indicators_table(inds, report_type),
        relationships_block=_relationships_table(edges, ind_map, report_type),
        timeline_block=_timeline_block(case, scans, report_type),
        notes_block=_notes_block(notes),
        followup_block=_followup_block(edges, scans, report_type),
    )
    return html


def render_pdf(html: str) -> bytes:
    """Convert HTML to PDF bytes using xhtml2pdf."""
    from xhtml2pdf import pisa

    buf = io.BytesIO()
    pisa_status = pisa.CreatePDF(html, dest=buf)
    if pisa_status.err:
        raise RuntimeError(f"PDF generation failed: {pisa_status.err}")
    return buf.getvalue()


def render_markdown_to_html(md_content: str, title: str) -> str:
    """Wrap existing markdown content in the HTML template for preview/download."""
    body = md_lib.markdown(md_content, extensions=["tables", "fenced_code"])
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; font-size: 14px; line-height: 1.7;
          color: #1e293b; background: #fff; max-width: 860px; margin: 40px auto; padding: 0 24px; }}
  h1,h2,h3 {{ color: #0f172a; }}
  h2 {{ border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th,td {{ border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; }}
  th {{ background: #f8fafc; }}
  code {{ background: #f1f5f9; padding: 2px 5px; border-radius: 3px; font-size: 12px; }}
  pre {{ background: #f1f5f9; padding: 12px; border-radius: 6px; overflow: auto; }}
</style>
</head>
<body>
{body}
</body>
</html>"""
