"""Report rendering — HTML template and PDF generation from case snapshots."""
from __future__ import annotations

import io
from datetime import datetime
from html import escape as html_escape
from typing import Any, Dict
from xml.sax.saxutils import escape as xml_escape

import markdown as md_lib


# ---------------------------------------------------------------------------
# HTML template (inline CSS — self-contained for download and xhtml2pdf)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title}</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 13px;
    line-height: 1.6;
    color: #1e293b;
    background: #ffffff;
    margin: 0;
    padding: 32px 48px;
  }}
  h1 {{ font-size: 22px; color: #0f172a; margin: 0 0 4px; }}
  h2 {{ font-size: 15px; color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin: 28px 0 10px; }}
  h3 {{ font-size: 13px; color: #334155; margin: 16px 0 6px; }}
  .meta {{ color: #64748b; font-size: 12px; margin-bottom: 24px; }}
  .badge {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 99px;
    font-size: 11px;
    font-weight: 600;
    margin-right: 4px;
  }}
  .badge-blue   {{ background: #dbeafe; color: #1d4ed8; }}
  .badge-green  {{ background: #dcfce7; color: #15803d; }}
  .badge-red    {{ background: #fee2e2; color: #b91c1c; }}
  .badge-amber  {{ background: #fef3c7; color: #b45309; }}
  .badge-slate  {{ background: #f1f5f9; color: #475569; }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 8px 0 16px;
    font-size: 12px;
  }}
  th {{
    background: #f8fafc;
    text-align: left;
    padding: 6px 10px;
    color: #475569;
    font-weight: 600;
    border-bottom: 2px solid #e2e8f0;
  }}
  td {{
    padding: 6px 10px;
    border-bottom: 1px solid #f1f5f9;
    vertical-align: top;
  }}
  tr:last-child td {{ border-bottom: none; }}
  .timeline-item {{ display: flex; gap: 12px; margin-bottom: 12px; }}
  .timeline-dot {{
    width: 8px; height: 8px;
    border-radius: 50%;
    background: #3b82f6;
    margin-top: 5px;
    flex-shrink: 0;
  }}
  .note-block {{
    background: #f8fafc;
    border-left: 3px solid #3b82f6;
    padding: 8px 12px;
    margin-bottom: 8px;
    border-radius: 0 4px 4px 0;
    font-size: 12px;
  }}
  .note-meta {{ color: #94a3b8; font-size: 11px; margin-bottom: 2px; }}
  .footer {{
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    color: #94a3b8;
    font-size: 11px;
  }}
  .confidence-bar-bg {{
    background: #e2e8f0;
    border-radius: 4px;
    height: 6px;
    width: 80px;
    display: inline-block;
    vertical-align: middle;
  }}
  .confidence-bar-fill {{
    background: #3b82f6;
    border-radius: 4px;
    height: 6px;
  }}
</style>
</head>
<body>

<h1>{title}</h1>
<div class="meta">
  <span class="badge badge-{status_cls}">{status}</span>
  <span class="badge badge-{priority_cls}">{priority}</span>
  &nbsp;·&nbsp; {case_number} &nbsp;·&nbsp; Generated {generated_at}
</div>

{description_block}

{dossier_block}

<h2>Scan Summary</h2>
{scans_block}

{indicators_block}

{relationships_block}

{timeline_block}

{notes_block}

{followup_block}

<div class="footer">
  Generated by OSIF v2 &nbsp;·&nbsp; {generated_at} &nbsp;·&nbsp; {title}
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_STATUS_CLS = {"open": "blue", "active": "green", "closed": "slate", "archived": "slate"}
_PRIORITY_CLS = {"critical": "red", "high": "amber", "medium": "blue", "low": "slate"}


def _fmt_dt(value) -> str:
    if not value:
        return "n/a"
    if isinstance(value, str):
        return value[:19].replace("T", " ")
    return value.strftime("%Y-%m-%d %H:%M")


def _conf_bar(confidence) -> str:
    try:
        pct = int(float(confidence) * 100)
    except (TypeError, ValueError):
        pct = 0
    fill = max(0, min(100, pct))
    return (
        f'<span class="confidence-bar-bg">'
        f'<span class="confidence-bar-fill" style="width:{fill}%"></span>'
        f'</span> <span style="font-size:11px;color:#64748b">{pct}%</span>'
    )


def _scans_table(scans: list) -> str:
    if not scans:
        return "<p style='color:#94a3b8'>No scans have been run for this case.</p>"
    rows = ""
    for s in scans:
        status_cls = {"completed": "green", "partial": "amber", "failed": "red"}.get(s.get("status", ""), "slate")
        rows += (
            f"<tr>"
            f"<td>{s.get('seed_value','')}</td>"
            f"<td><span class='badge badge-blue'>{s.get('seed_kind','')}</span></td>"
            f"<td><span class='badge badge-{status_cls}'>{s.get('status','')}</span></td>"
            f"<td>{s.get('progress',0)}/{s.get('total_modules',0)}</td>"
            f"<td style='color:#94a3b8;font-size:11px'>{_fmt_dt(s.get('created_at'))}</td>"
            f"</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Target</th><th>Kind</th><th>Status</th><th>Modules</th><th>Started</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table>"
    )


def _indicators_table(indicators: list, report_type: str) -> str:
    if report_type not in {"technical", "full", "summary"}:
        return ""
    if not indicators:
        return "<h2>Indicators</h2><p style='color:#94a3b8'>No indicators found.</p>"
    rows = ""
    for ind in indicators[:50]:
        kind_cls = {
            "domain": "blue", "ip": "green", "email": "amber",
            "hostname": "slate", "url": "slate",
        }.get(ind.get("kind", ""), "slate")
        rows += (
            f"<tr>"
            f"<td><span class='badge badge-{kind_cls}'>{ind.get('kind','')}</span></td>"
            f"<td style='font-family:monospace'>{ind.get('value','')}</td>"
            f"<td>{_conf_bar(ind.get('confidence', 0))}</td>"
            f"<td style='color:#94a3b8;font-size:11px'>{ind.get('source_module','')}</td>"
            f"</tr>"
        )
    return (
        "<h2>Indicators</h2>"
        "<table><thead><tr>"
        "<th>Kind</th><th>Value</th><th>Confidence</th><th>Source</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table>"
    )


def _relationships_table(edges: list, indicator_map: dict, report_type: str) -> str:
    if report_type not in {"technical", "full"}:
        return ""
    if not edges:
        return "<h2>Relationships</h2><p style='color:#94a3b8'>No relationships found.</p>"
    rows = ""
    for e in edges[:50]:
        src = indicator_map.get(str(e.get("src_id", "")), {})
        dst = indicator_map.get(str(e.get("dst_id", "")), {})
        rows += (
            f"<tr>"
            f"<td style='font-family:monospace'>{src.get('value', str(e.get('src_id','')))}</td>"
            f"<td style='color:#3b82f6;font-weight:600'>{e.get('relationship_type','')}</td>"
            f"<td style='font-family:monospace'>{dst.get('value', str(e.get('dst_id','')))}</td>"
            f"<td style='color:#94a3b8;font-size:11px'>{e.get('source_module','')}</td>"
            f"<td>{_conf_bar(e.get('confidence', 0))}</td>"
            f"</tr>"
        )
    return (
        "<h2>Relationships</h2>"
        "<table><thead><tr>"
        "<th>Source</th><th>Relationship</th><th>Target</th><th>Module</th><th>Confidence</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table>"
    )


def _timeline_block(case_data: dict, scans: list, report_type: str) -> str:
    if report_type not in {"timeline", "full"}:
        return ""
    events = [{"time": case_data.get("created_at", ""), "label": "Case created", "detail": case_data.get("title", "")}]
    for s in scans:
        events.append({"time": s.get("created_at", ""), "label": f"Scan started: {s.get('seed_value','')}", "detail": s.get("seed_kind", "")})
        if s.get("finished_at"):
            events.append({"time": s.get("finished_at", ""), "label": f"Scan {s.get('status','done')}: {s.get('seed_value','')}", "detail": ""})
    events.sort(key=lambda e: e.get("time") or "")
    items = "".join(
        f"<div class='timeline-item'><div class='timeline-dot'></div><div>"
        f"<div style='font-weight:600'>{ev['label']}</div>"
        f"<div style='color:#64748b;font-size:12px'>{ev.get('detail','')} &nbsp;·&nbsp; {_fmt_dt(ev['time'])}</div>"
        f"</div></div>"
        for ev in events
    )
    return f"<h2>Timeline</h2>{items}"


def _notes_block(notes: list) -> str:
    if not notes:
        return "<h2>Notes</h2><p style='color:#94a3b8'>No case notes recorded.</p>"
    blocks = "".join(
        f"<div class='note-block'>"
        f"<div class='note-meta'>{_fmt_dt(n.get('created_at'))} · {n.get('author') or 'Analyst'}</div>"
        f"{n.get('content','')}"
        f"</div>"
        for n in notes
    )
    return f"<h2>Notes</h2>{blocks}"


def _followup_block(edges: list, scans: list, report_type: str) -> str:
    if report_type not in {"summary", "full"}:
        return ""
    items = []
    high_signal = [e for e in edges if e.get("relationship_type", "").upper() in
                   {"FOUND_IN_BREACH", "HAS_VULNERABILITY", "FLAGGED_AS", "HAS_REPUTATION"}]
    if high_signal:
        items.append(f"Review {len(high_signal)} high-signal relationship(s) for validation.")
    if any(s.get("status") in {"partial", "failed", "error"} for s in scans):
        items.append("Review failed or partial scans and rerun missing modules where appropriate.")
    items.append("Validate all findings against source evidence before external distribution.")
    rows = "".join(f"<li>{i}</li>" for i in items)
    return f"<h2>Analyst Follow-Up</h2><ul>{rows}</ul>"


def _dossier_block(dossier: dict | None, report_type: str) -> str:
    if not dossier or report_type not in {"dossier", "full"}:
        return ""

    def esc(value) -> str:
        return html_escape(str(value or ""))

    subject = dossier.get("subject", {})
    summary = dossier.get("summary", {})
    metrics = (
        "<table><thead><tr><th>Subject</th><th>Confirmed Entities</th><th>Verified Links</th>"
        "<th>Locations</th><th>Open Leads</th></tr></thead><tbody><tr>"
        f"<td>{esc(subject.get('name') or 'Unknown')}</td>"
        f"<td>{summary.get('confirmed_entities', 0)}</td>"
        f"<td>{summary.get('verified_relationships', 0)}</td>"
        f"<td>{summary.get('locations', 0)}</td>"
        f"<td>{summary.get('open_leads', 0)}</td>"
        "</tr></tbody></table>"
    )

    relationships = dossier.get("relationships") or []
    relationship_rows = "".join(
        "<tr>"
        f"<td>{esc((rel.get('source') or {}).get('label') or (rel.get('source') or {}).get('value') or (rel.get('source') or {}).get('id'))}</td>"
        f"<td>{esc(rel.get('relationship'))}</td>"
        f"<td>{esc((rel.get('target') or {}).get('label') or (rel.get('target') or {}).get('value') or (rel.get('target') or {}).get('id'))}</td>"
        f"<td>{esc(rel.get('verification_status'))}</td>"
        "</tr>"
        for rel in relationships[:25]
    )
    relationships_block = (
        "<h2>Verified Relationships</h2><table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th><th>Status</th></tr></thead>"
        f"<tbody>{relationship_rows}</tbody></table>"
        if relationship_rows else
        "<h2>Verified Relationships</h2><p style='color:#94a3b8'>No verified relationships recorded.</p>"
    )

    locations = dossier.get("locations") or []
    location_rows = "".join(
        "<tr>"
        f"<td>{esc(loc.get('label') or loc.get('address_text') or 'Location')}</td>"
        f"<td>{esc(loc.get('latitude'))}, {esc(loc.get('longitude'))}</td>"
        f"<td>{esc(loc.get('precision'))}</td>"
        f"<td>{esc(loc.get('verification_status'))}</td>"
        "</tr>"
        for loc in locations[:20]
    )
    locations_block = (
        "<h2>Locations</h2><table><thead><tr><th>Label</th><th>Coordinates</th><th>Precision</th><th>Status</th></tr></thead>"
        f"<tbody>{location_rows}</tbody></table>"
        if location_rows else
        "<h2>Locations</h2><p style='color:#94a3b8'>No mapped locations recorded.</p>"
    )

    timeline = dossier.get("timeline") or []
    timeline_rows = "".join(
        "<tr>"
        f"<td>{_fmt_dt(event.get('occurred_at'))}</td>"
        f"<td>{esc(event.get('title'))}</td>"
        f"<td>{esc(event.get('event_type'))}</td>"
        f"<td>{esc((event.get('location') or {}).get('label'))}</td>"
        "</tr>"
        for event in timeline[:25]
    )
    timeline_block = (
        "<h2>Investigation Timeline</h2><table><thead><tr><th>When</th><th>Event</th><th>Type</th><th>Location</th></tr></thead>"
        f"<tbody>{timeline_rows}</tbody></table>"
        if timeline_rows else
        "<h2>Investigation Timeline</h2><p style='color:#94a3b8'>No confirmed timeline events recorded.</p>"
    )

    evidence = dossier.get("evidence") or []
    hidden = summary.get("sensitive_evidence_hidden", 0)
    sensitive_note = (
        f"<p><span class='badge badge-amber'>{hidden} sensitive evidence item(s) excluded</span></p>"
        if hidden else ""
    )
    evidence_rows = "".join(
        "<tr>"
        f"<td>{esc(item.get('title'))}</td>"
        f"<td>{esc(item.get('evidence_type'))}</td>"
        f"<td>{esc(item.get('file_name') or item.get('source_url') or item.get('source_type'))}</td>"
        f"<td>{esc(item.get('chain_of_custody_status'))}</td>"
        "</tr>"
        for item in evidence[:25]
    )
    evidence_block = (
        "<h2>Evidence Summary</h2>"
        f"{sensitive_note}<table><thead><tr><th>Title</th><th>Type</th><th>Source</th><th>Custody</th></tr></thead>"
        f"<tbody>{evidence_rows}</tbody></table>"
        if evidence_rows else
        f"<h2>Evidence Summary</h2>{sensitive_note}<p style='color:#94a3b8'>No evidence available under current filters.</p>"
    )

    leads = dossier.get("leads") or []
    lead_rows = "".join(
        "<tr>"
        f"<td>{esc(lead.get('label'))}</td>"
        f"<td>{esc(lead.get('target_type'))}</td>"
        f"<td>{esc(lead.get('review_status'))}</td>"
        f"<td>{esc(lead.get('source_type'))}</td>"
        "</tr>"
        for lead in leads[:25]
    )
    leads_block = (
        "<h2>Open Leads</h2><table><thead><tr><th>Lead</th><th>Target</th><th>Status</th><th>Source</th></tr></thead>"
        f"<tbody>{lead_rows}</tbody></table>"
        if lead_rows else
        "<h2>Open Leads</h2><p style='color:#94a3b8'>No open leads.</p>"
    )

    return f"<h2>Subject Dossier</h2>{metrics}{relationships_block}{locations_block}{timeline_block}{evidence_block}{leads_block}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_snapshot(case, scans: list, indicators: list, edges: list, notes: list) -> Dict[str, Any]:
    """Build a point-in-time JSON snapshot of the case data."""
    def _ind(i):
        return {
            "id": str(i.id), "kind": i.kind, "value": i.value,
            "confidence": float(i.confidence) if i.confidence is not None else None,
            "source_module": (i.meta or {}).get("source_module", ""),
        }

    def _edge(e):
        return {
            "src_id": str(e.src_id), "dst_id": str(e.dst_id),
            "relationship_type": e.relationship_type,
            "source_module": e.source_module,
            "confidence": float(e.confidence) if e.confidence is not None else None,
        }

    def _scan(s):
        return {
            "id": str(s.id), "seed_value": s.seed_value, "seed_kind": s.seed_kind,
            "status": s.status, "progress": s.progress, "total_modules": s.total_modules,
            "created_at": s.created_at.isoformat() if s.created_at else None,
            "finished_at": s.finished_at.isoformat() if s.finished_at else None,
        }

    def _note(n):
        return {
            "id": str(n.id), "content": n.content,
            "author": getattr(n, "author", None),
            "created_at": n.created_at.isoformat() if n.created_at else None,
        }

    return {
        "case": {
            "id": str(case.id), "case_number": case.case_number, "title": case.title,
            "description": case.description, "status": case.status, "priority": case.priority,
            "assigned_to": case.assigned_to, "client": case.client,
            "closed_reason": getattr(case, "closed_reason", None),
            "created_at": case.created_at.isoformat() if case.created_at else None,
        },
        "scans": [_scan(s) for s in scans],
        "indicators": [_ind(i) for i in indicators],
        "edges": [_edge(e) for e in edges],
        "notes": [_note(n) for n in notes],
        "generated_at": datetime.utcnow().isoformat(),
    }


def render_html(snapshot: Dict[str, Any], title: str, report_type: str) -> str:
    """Render a self-contained HTML report from a snapshot."""
    case     = snapshot.get("case", {})
    scans    = snapshot.get("scans", [])
    inds     = snapshot.get("indicators", [])
    edges    = snapshot.get("edges", [])
    notes    = snapshot.get("notes", [])
    gen_at   = snapshot.get("generated_at", datetime.utcnow().isoformat())

    ind_map = {i["id"]: i for i in inds}

    desc_block = (
        f"<h2>Case Description</h2><p>{case.get('description','')}</p>"
        if case.get("description") else ""
    )

    html = _HTML_TEMPLATE.format(
        title=title,
        case_number=case.get("case_number", ""),
        status=case.get("status", ""),
        status_cls=_STATUS_CLS.get(case.get("status", ""), "slate"),
        priority=case.get("priority", ""),
        priority_cls=_PRIORITY_CLS.get(case.get("priority", ""), "slate"),
        generated_at=_fmt_dt(gen_at),
        description_block=desc_block,
        dossier_block=_dossier_block(snapshot.get("dossier"), report_type),
        scans_block=_scans_table(scans),
        indicators_block=_indicators_table(inds, report_type),
        relationships_block=_relationships_table(edges, ind_map, report_type),
        timeline_block=_timeline_block(case, scans, report_type),
        notes_block=_notes_block(notes),
        followup_block=_followup_block(edges, scans, report_type),
    )
    return html


def render_pdf(snapshot: Dict[str, Any], title: str, report_type: str) -> bytes:
    """Render a structured PDF from a snapshot using reportlab (pure Python, no system deps)."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )

    case  = snapshot.get("case", {})
    scans = snapshot.get("scans", [])
    inds  = snapshot.get("indicators", [])
    edges = snapshot.get("edges", [])
    notes = snapshot.get("notes", [])
    dossier = snapshot.get("dossier")
    gen_at = snapshot.get("generated_at", "")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )

    styles = getSampleStyleSheet()
    h1  = ParagraphStyle("h1",  parent=styles["Heading1"], fontSize=18, spaceAfter=4, textColor=colors.HexColor("#0f172a"))
    h2  = ParagraphStyle("h2",  parent=styles["Heading2"], fontSize=12, spaceBefore=14, spaceAfter=4, textColor=colors.HexColor("#1e293b"))
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=9, leading=14, textColor=colors.HexColor("#334155"))
    muted = ParagraphStyle("muted", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#64748b"))
    mono = ParagraphStyle("mono", parent=styles["Normal"], fontSize=8, fontName="Courier", textColor=colors.HexColor("#1e293b"))

    ACCENT   = colors.HexColor("#3b82f6")
    HDR_BG   = colors.HexColor("#f8fafc")
    BORDER   = colors.HexColor("#e2e8f0")
    ROW_ALT  = colors.HexColor("#f8fafc")

    def tbl_style(has_alt=True):
        base = [
            ("BACKGROUND",   (0, 0), (-1, 0),  HDR_BG),
            ("TEXTCOLOR",    (0, 0), (-1, 0),  colors.HexColor("#475569")),
            ("FONTSIZE",     (0, 0), (-1, 0),  8),
            ("FONTNAME",     (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("BOTTOMPADDING",(0, 0), (-1, 0),  6),
            ("TOPPADDING",   (0, 0), (-1, 0),  6),
            ("FONTSIZE",     (0, 1), (-1, -1), 8),
            ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
            ("TOPPADDING",   (0, 1), (-1, -1), 4),
            ("BOTTOMPADDING",(0, 1), (-1, -1), 4),
            ("GRID",         (0, 0), (-1, -1), 0.5, BORDER),
            ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ]
        return TableStyle(base)

    story = []

    # ── Title & meta ──────────────────────────────────────────
    story.append(Paragraph(title, h1))
    story.append(Paragraph(
        f"{case.get('case_number','')} &nbsp;·&nbsp; "
        f"Status: <b>{case.get('status','')}</b> &nbsp;·&nbsp; "
        f"Severity: <b>{case.get('priority','')}</b> &nbsp;·&nbsp; "
        f"Generated: {_fmt_dt(gen_at)}",
        muted
    ))
    if case.get("assigned_to"):
        story.append(Paragraph(f"Analyst: {case['assigned_to']}", muted))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=8))

    if case.get("description"):
        story.append(Paragraph("Case Description", h2))
        story.append(Paragraph(case["description"], body))

    if dossier and report_type in {"dossier", "full"}:
        subject = dossier.get("subject", {})
        summary = dossier.get("summary", {})
        story.append(Paragraph("Subject Dossier", h2))
        story.append(Paragraph(
            f"<b>Subject:</b> {xml_escape(str(subject.get('name') or 'Unknown'))} &nbsp; "
            f"<b>Confirmed entities:</b> {summary.get('confirmed_entities', 0)} &nbsp; "
            f"<b>Verified links:</b> {summary.get('verified_relationships', 0)} &nbsp; "
            f"<b>Locations:</b> {summary.get('locations', 0)} &nbsp; "
            f"<b>Open leads:</b> {summary.get('open_leads', 0)}",
            body,
        ))

        relationships = dossier.get("relationships") or []
        story.append(Paragraph("Verified Relationships", h2))
        if relationships:
            data = [["Source", "Relationship", "Target", "Status"]]
            for rel in relationships[:25]:
                source = rel.get("source") or {}
                target = rel.get("target") or {}
                data.append([
                    Paragraph(xml_escape(str(source.get("label") or source.get("value") or source.get("id") or "")), body),
                    xml_escape(str(rel.get("relationship") or "")),
                    Paragraph(xml_escape(str(target.get("label") or target.get("value") or target.get("id") or "")), body),
                    xml_escape(str(rel.get("verification_status") or "")),
                ])
            t = Table(data, colWidths=[45*mm, 35*mm, 45*mm, 34*mm])
            t.setStyle(tbl_style())
            story.append(t)
        else:
            story.append(Paragraph("No verified relationships recorded.", muted))

        locations = dossier.get("locations") or []
        story.append(Paragraph("Locations", h2))
        if locations:
            data = [["Label", "Coordinates", "Precision", "Status"]]
            for loc in locations[:20]:
                data.append([
                    Paragraph(xml_escape(str(loc.get("label") or loc.get("address_text") or "Location")), body),
                    f"{loc.get('latitude')}, {loc.get('longitude')}",
                    xml_escape(str(loc.get("precision") or "")),
                    xml_escape(str(loc.get("verification_status") or "")),
                ])
            t = Table(data, colWidths=[58*mm, 42*mm, 26*mm, 33*mm])
            t.setStyle(tbl_style())
            story.append(t)
        else:
            story.append(Paragraph("No mapped locations recorded.", muted))

        timeline = dossier.get("timeline") or []
        story.append(Paragraph("Investigation Timeline", h2))
        if timeline:
            data = [["When", "Event", "Type", "Location"]]
            for event in timeline[:25]:
                location = event.get("location") or {}
                data.append([
                    _fmt_dt(event.get("occurred_at")),
                    Paragraph(xml_escape(str(event.get("title") or "")), body),
                    xml_escape(str(event.get("event_type") or "")),
                    Paragraph(xml_escape(str(location.get("label") or "")), body),
                ])
            t = Table(data, colWidths=[36*mm, 62*mm, 30*mm, 31*mm])
            t.setStyle(tbl_style())
            story.append(t)
        else:
            story.append(Paragraph("No confirmed timeline events recorded.", muted))

        evidence = dossier.get("evidence") or []
        story.append(Paragraph("Evidence Summary", h2))
        hidden = summary.get("sensitive_evidence_hidden", 0)
        if hidden:
            story.append(Paragraph(f"{hidden} sensitive evidence item(s) excluded.", muted))
        if evidence:
            data = [["Title", "Type", "Source", "Custody"]]
            for item in evidence[:25]:
                data.append([
                    Paragraph(xml_escape(str(item.get("title") or "")), body),
                    xml_escape(str(item.get("evidence_type") or "")),
                    Paragraph(xml_escape(str(item.get("file_name") or item.get("source_url") or item.get("source_type") or "")), body),
                    xml_escape(str(item.get("chain_of_custody_status") or "")),
                ])
            t = Table(data, colWidths=[50*mm, 28*mm, 54*mm, 27*mm])
            t.setStyle(tbl_style())
            story.append(t)
        else:
            story.append(Paragraph("No evidence available under current filters.", muted))

        leads = dossier.get("leads") or []
        story.append(Paragraph("Open Leads", h2))
        if leads:
            data = [["Lead", "Target", "Status", "Source"]]
            for lead in leads[:25]:
                data.append([
                    Paragraph(xml_escape(str(lead.get("label") or "")), body),
                    xml_escape(str(lead.get("target_type") or "")),
                    xml_escape(str(lead.get("review_status") or "")),
                    xml_escape(str(lead.get("source_type") or "")),
                ])
            t = Table(data, colWidths=[62*mm, 30*mm, 32*mm, 35*mm])
            t.setStyle(tbl_style())
            story.append(t)
        else:
            story.append(Paragraph("No open leads.", muted))

    # ── Scans ─────────────────────────────────────────────────
    story.append(Paragraph("Scan Summary", h2))
    if scans:
        data = [["Target", "Kind", "Status", "Modules", "Started"]]
        for s in scans:
            data.append([
                Paragraph(s.get("seed_value", ""), mono),
                s.get("seed_kind", ""),
                s.get("status", ""),
                f"{s.get('progress',0)}/{s.get('total_modules',0)}",
                _fmt_dt(s.get("created_at", "")),
            ])
        t = Table(data, colWidths=[55*mm, 22*mm, 22*mm, 20*mm, 40*mm])
        t.setStyle(tbl_style())
        story.append(t)
    else:
        story.append(Paragraph("No scans have been run for this case.", muted))

    # ── Indicators ────────────────────────────────────────────
    if report_type in {"technical", "full", "summary"} and inds:
        story.append(Paragraph("Indicators", h2))
        data = [["Kind", "Value", "Confidence", "Source"]]
        for i in inds[:50]:
            conf = i.get("confidence")
            conf_str = f"{int(float(conf)*100)}%" if conf is not None else "—"
            data.append([
                i.get("kind", ""),
                Paragraph(i.get("value", ""), mono),
                conf_str,
                i.get("source_module", ""),
            ])
        t = Table(data, colWidths=[22*mm, 80*mm, 22*mm, 35*mm])
        t.setStyle(tbl_style())
        story.append(t)

    # ── Relationships ─────────────────────────────────────────
    if report_type in {"technical", "full"} and edges:
        ind_map = {i["id"]: i for i in inds}
        story.append(Paragraph("Relationships", h2))
        data = [["Source", "Relationship", "Target", "Module", "Conf"]]
        for e in edges[:50]:
            src = ind_map.get(e.get("src_id", ""), {})
            dst = ind_map.get(e.get("dst_id", ""), {})
            conf = e.get("confidence")
            conf_str = f"{int(float(conf)*100)}%" if conf is not None else "—"
            data.append([
                Paragraph(src.get("value", str(e.get("src_id",""))), mono),
                e.get("relationship_type", ""),
                Paragraph(dst.get("value", str(e.get("dst_id",""))), mono),
                e.get("source_module", ""),
                conf_str,
            ])
        t = Table(data, colWidths=[40*mm, 32*mm, 40*mm, 30*mm, 17*mm])
        t.setStyle(tbl_style())
        story.append(t)

    # ── Timeline ──────────────────────────────────────────────
    if report_type in {"timeline", "full"}:
        story.append(Paragraph("Timeline", h2))
        events = [{"time": case.get("created_at",""), "label": "Case created", "detail": case.get("title","")}]
        for s in scans:
            events.append({"time": s.get("created_at",""), "label": f"Scan started", "detail": s.get("seed_value","")})
            if s.get("finished_at"):
                events.append({"time": s.get("finished_at",""), "label": f"Scan {s.get('status','done')}", "detail": s.get("seed_value","")})
        events.sort(key=lambda e: e.get("time") or "")
        for ev in events:
            story.append(Paragraph(f"<b>{_fmt_dt(ev['time'])}</b> — {ev['label']}: {ev.get('detail','')}", body))

    # ── Notes ─────────────────────────────────────────────────
    story.append(Paragraph("Notes", h2))
    if notes:
        for n in notes:
            story.append(Paragraph(f"<i>{_fmt_dt(n.get('created_at',''))}</i>", muted))
            story.append(Paragraph(n.get("content", ""), body))
            story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("No case notes recorded.", muted))

    # ── Follow-up ─────────────────────────────────────────────
    if report_type in {"summary", "full"}:
        story.append(Paragraph("Analyst Follow-Up", h2))
        high_signal = [e for e in edges if e.get("relationship_type","").upper() in
                       {"FOUND_IN_BREACH","HAS_VULNERABILITY","FLAGGED_AS","HAS_REPUTATION"}]
        if high_signal:
            story.append(Paragraph(f"• Review {len(high_signal)} high-signal relationship(s) for validation.", body))
        if any(s.get("status") in {"partial","failed","error"} for s in scans):
            story.append(Paragraph("• Review failed or partial scans and rerun missing modules.", body))
        story.append(Paragraph("• Validate all findings against source evidence before external distribution.", body))

    # ── Footer ────────────────────────────────────────────────
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Paragraph(f"Generated by OSIF v2 · {_fmt_dt(gen_at)} · {title}", muted))

    doc.build(story)
    return buf.getvalue()


def render_markdown_to_html(md_content: str, title: str) -> str:
    """Wrap existing markdown content in the HTML template for preview/download."""
    body = md_lib.markdown(md_content, extensions=["tables", "fenced_code"])
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; font-size: 14px; line-height: 1.7;
          color: #1e293b; background: #fff; max-width: 860px; margin: 40px auto; padding: 0 24px; }}
  h1,h2,h3 {{ color: #0f172a; }}
  h2 {{ border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th,td {{ border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; }}
  th {{ background: #f8fafc; }}
  code {{ background: #f1f5f9; padding: 2px 5px; border-radius: 3px; font-size: 12px; }}
  pre {{ background: #f1f5f9; padding: 12px; border-radius: 6px; overflow: auto; }}
</style>
</head>
<body>
{body}
</body>
</html>"""
