"""Add scan_templates table - Phase 3

Revision ID: 4618a5e43fd7
Revises: 2728f52b547e
Create Date: 2026-07-01 04:46:16.000749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4618a5e43fd7'
down_revision: Union[str, None] = '2728f52b547e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
