"""add closed_reason to cases

Revision ID: a9166d45ecd7
Revises: 9f35c3c7d8a1
Create Date: 2026-07-02 06:08:45.185336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9166d45ecd7'
down_revision: Union[str, None] = '9f35c3c7d8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('closed_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'closed_reason')
    # ### end Alembic commands ###
