"""Add scan_templates table for Phase 3

Revision ID: ee1aa765cff4
Revises: fc58314d65ae
Create Date: 2026-07-01 04:44:29.846343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1aa765cff4'
down_revision: Union[str, None] = 'fc58314d65ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
