"""Initial schema

Revision ID: fc58314d65ae
Revises: 
Create Date: 2026-07-01 04:30:14.867709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc58314d65ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('target_aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('target_location', sa.String(length=255), nullable=True),
    sa.Column('target_dob', sa.Date(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicators_kind_value', 'indicators', ['kind', 'value'], unique=True)
    op.create_index('idx_indicators_meta_gin', 'indicators', ['meta'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_indicators_kind'), 'indicators', ['kind'], unique=False)
    op.create_index(op.f('ix_indicators_value'), 'indicators', ['value'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('src_id', sa.UUID(), nullable=False),
    sa.Column('dst_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source_module', sa.String(length=100), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edges_unique', 'edges', ['src_id', 'dst_id', 'relationship_type', 'source_module'], unique=True)
    op.create_index(op.f('ix_edges_dst_id'), 'edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_edges_relationship_type'), 'edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_edges_src_id'), 'edges', ['src_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('seed_value', sa.Text(), nullable=False),
    sa.Column('seed_kind', sa.String(length=50), nullable=False),
    sa.Column('modules', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_modules', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('collected_by', sa.String(length=100), nullable=True),
    sa.Column('chain_of_custody', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_table('scan_findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id', 'edge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_findings')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('scans')
    op.drop_index(op.f('ix_edges_src_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_relationship_type'), table_name='edges')
    op.drop_index(op.f('ix_edges_dst_id'), table_name='edges')
    op.drop_index('idx_edges_unique', table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_indicators_value'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_kind'), table_name='indicators')
    op.drop_index('idx_indicators_meta_gin', table_name='indicators', postgresql_using='gin')
    op.drop_index('idx_indicators_kind_value', table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('cases')
    # ### end Alembic commands ###
